export const config = {
  API_ENDPOINT: process.env.REACT_APP_API_END_POINT,
  APP_IMAGE_END_POINT: process.env.REACT_APP_IMAGE_END_POINT,
  APP_GOOGLE_MAP_API_KEY: process.env.REACT_APP_GOOGLE_MAP_API_KEY,
};
